# Changes here will be overwritten by Copier
_commit: v2.0.5
_src_path: gh:lincc-frameworks/python-project-template
author_email: parthenope.ap@gmail.com
author_name: parthenope-ap
create_example_module: true
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: lsst_comet_interceptor_target_reduction
project_license: MIT
project_name: lsst-comet-interceptor-target-reduction
project_organization: parthenope-ap
python_versions:
- '3.9'
- '3.10'
- '3.11'
